//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CycoPath.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string IdData { get; set; }
        public string ConnectorName { get; set; }
        public string Description { get; set; }
        public string StyleURl { get; set; }
        public string altMode { get; set; }
        public string Coordinates { get; set; }
    }
}
